/*
 * generated by Fujaba - CodeGen2
 */
import java.io.File;
import de.upb.tools.sdm.*; // requires Fujaba5/libs/RuntimeTools.jar in classpath
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath


public class RegularFile extends AbstractFile
{



   public  RegularFile (String name )
   {
      boolean fujaba__Success = false;
      File f = null;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // create object f
         f = new java.io.File(name);

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if ( !( fujaba__Success ) )
      {
         return ;

      }
      // // <add comment>
      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object f is really bound
         JavaSDM.ensure ( f != null );
         // constraint f.isFile()
         JavaSDM.ensure ( f.isFile() );
         // create link file from f to this
         f.setFile (this);

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if ( !( fujaba__Success ) )
      {
         return ;

      }
      return ;
   }

   public void accept (Visitor visitor )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object visitor is really bound
         JavaSDM.ensure ( visitor != null );
         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return ;
   }

   public long getFileSize ()
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object f is really bound
         JavaSDM.ensure ( f != null );
         // check link file from f to this
         JavaSDM.ensure (this.equals (f.getFile ()));

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return f.length();
   }

   public static final String PROPERTY_NAME = "name";

   @Property( name = PROPERTY_NAME, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private String name;

   @Property( name = PROPERTY_NAME )
   private void setName (String value)
   {
      this.name = value;
   }

   private RegularFile withName (String value)
   {
      setName (value);
      return this;
   }

   @Property( name = PROPERTY_NAME )
   private String getName ()
   {
      return this.name;
   }

}


