/*
 * generated by Fujaba - CodeGen2
 */
import de.upb.tools.sdm.*; // requires Fujaba5/libs/RuntimeTools.jar in classpath
import java.util.ArrayList;
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath


public class SearchVisitor extends Visitor
{



   public ArrayList findAll (AbstractFile file , String searchPattern )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object file is really bound
         JavaSDM.ensure ( file != null );
         // collabStat call
         searchPattern = searchPattern;
         // collabStat call
         file.accept(this);
         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return this.foundPaths;
   }

   public static final String PROPERTY_FOUND_PATHS = "foundPaths";

   @Property( name = PROPERTY_FOUND_PATHS, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private ArrayList foundPaths;

   @Property( name = PROPERTY_FOUND_PATHS )
   public void setFoundPaths (ArrayList value)
   {
      this.foundPaths = value;
   }

   public SearchVisitor withFoundPaths (ArrayList value)
   {
      setFoundPaths (value);
      return this;
   }

   @Property( name = PROPERTY_FOUND_PATHS )
   public ArrayList getFoundPaths ()
   {
      return this.foundPaths;
   }

   public static final String PROPERTY_SEARCH_PATTERN = "searchPattern";

   @Property( name = PROPERTY_SEARCH_PATTERN, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private String searchPattern;

   @Property( name = PROPERTY_SEARCH_PATTERN )
   public void setSearchPattern (String value)
   {
      this.searchPattern = value;
   }

   public SearchVisitor withSearchPattern (String value)
   {
      setSearchPattern (value);
      return this;
   }

   @Property( name = PROPERTY_SEARCH_PATTERN )
   public String getSearchPattern ()
   {
      return this.searchPattern;
   }

   public void visit (Directory d )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object d is really bound
         JavaSDM.ensure ( d != null );
         // constraint d.getTheItemName() == searchPattern
         JavaSDM.ensure ( d.getTheItemName() == searchPattern );
         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if ( fujaba__Success )
      {
         // story pattern successor
         try 
         {
            fujaba__Success = false; 

            // collabStat call
            this.foundPaths.add(d.getName());
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }


      }
      return ;
   }

   public void visit (RegularFile f )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object f is really bound
         JavaSDM.ensure ( f != null );
         // attribute condition searchPattern == f.getTheItemName()
         JavaSDM.ensure ( this.getSearchPattern () == f.getTheItemName() );

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if ( fujaba__Success )
      {
         // story pattern storypatternwithparams
         try 
         {
            fujaba__Success = false; 

            // check object f is really bound
            JavaSDM.ensure ( f != null );
            // collabStat call
            this.foundPaths.add(f.getAbsolutePath());
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }


      }
      return ;
   }

   public void visit (Root root )
   {

   }

}


