/*
 * generated by Fujaba - CodeGen2
 */
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath
import de.upb.tools.sdm.*; // requires Fujaba5/libs/RuntimeTools.jar in classpath


public class SearchVisitor extends Visitor
{



   public static final String PROPERTY_FOUND_PATHS = "foundPaths";

   @Property( name = PROPERTY_FOUND_PATHS, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private String[] foundPaths;

   @Property( name = PROPERTY_FOUND_PATHS )
   private void setFoundPaths (String[] value)
   {
      this.foundPaths = value;
   }

   private SearchVisitor withFoundPaths (String[] value)
   {
      setFoundPaths (value);
      return this;
   }

   @Property( name = PROPERTY_FOUND_PATHS )
   private String[] getFoundPaths ()
   {
      return this.foundPaths;
   }

   public static final String PROPERTY_SEARCH_PATTERN = "searchPattern";

   @Property( name = PROPERTY_SEARCH_PATTERN, kind = ReferenceHandler.ReferenceKind.ATTRIBUTE )
   private String searchPattern;

   @Property( name = PROPERTY_SEARCH_PATTERN )
   private void setSearchPattern (String value)
   {
      this.searchPattern = value;
   }

   private SearchVisitor withSearchPattern (String value)
   {
      setSearchPattern (value);
      return this;
   }

   @Property( name = PROPERTY_SEARCH_PATTERN )
   private String getSearchPattern ()
   {
      return this.searchPattern;
   }

   public void visit (Directory d )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // attribute condition searchPattern == d.name
         JavaSDM.ensure ( JavaSDM.stringCompare ((String) this.getSearchPattern (), d.name) == 0 );

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if ( fujaba__Success )
      {
         // story pattern successor
         try 
         {
            fujaba__Success = false; 

            // collabStat call
            this.foundPaths.add(d.name);
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }


      }
      return ;
   }

   public void visit (RegularFile f )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object f is really bound
         JavaSDM.ensure ( f != null );
         // attribute condition searchPattern == f.name
         JavaSDM.ensure ( JavaSDM.stringCompare ((String) this.getSearchPattern (), f.name) == 0 );

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      if ( fujaba__Success )
      {
         // story pattern storypatternwithparams
         try 
         {
            fujaba__Success = false; 

            // check object f is really bound
            JavaSDM.ensure ( f != null );
            // collabStat call
            this.foundPaths.add(f.getAbsolutePath());
            fujaba__Success = true;
         }
         catch ( JavaSDMException fujaba__InternalException )
         {
            fujaba__Success = false;
         }


      }
      return ;
   }

   public void visit (Root root )
   {
   }

}


