/*
 * generated by Fujaba - CodeGen2
 */
import de.upb.tools.sdm.*; // requires Fujaba5/libs/RuntimeTools.jar in classpath


public class Visitor
{



   public int countFiles (AbstractFile file )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwiththis
      try 
      {
         fujaba__Success = false; 

         // check object file is really bound
         JavaSDM.ensure ( file != null );
         // collabStat call
         file.f.accept(this);
         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return this.fileCount;
   }

   public String[] findAll (String extension )
   {
      boolean fujaba__Success = false;

      return null;
   }

   public String[] findAll (String searchPattern , AbstractFile file )
   {
      boolean fujaba__Success = false;

      // story pattern storypatternwithparams
      try 
      {
         fujaba__Success = false; 

         // check object file is really bound
         JavaSDM.ensure ( file != null );
         // collabStat call
         searchPattern = searchPattern;
         // collabStat call
         file.file.accept(this);
         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

      return this.foundPaths;
   }

   public void visit (Directory directory )
   {
   }

   public void visit (RegularFile file )
   {
   }

   public void visit (Root root )
   {
   }

   public void removeYou()
   {
   }
}


