/*
 * generated by Fujaba - CodeGen2
 */
import java.util.ArrayList;


public class Visitor
{



   public long countFiles (AbstractFile file )
   {

      return 0;
   }

   public ArrayList findAll (String extension )
   {
      boolean fujaba__Success = false;

      return null;
   }

   public ArrayList findAll (String searchPattern , AbstractFile file )
   {

      return null;
   }

   public void visit (Directory directory )
   {

      return ;
   }

   public void visit (RegularFile file )
   {

   }

   public void visit (Root root )
   {
   }

   public void removeYou()
   {
   }
}


