/*
 * generated by Fujaba - CodeGen2
 */
import de.uni_kassel.features.annotation.util.Property; // requires Fujaba5/libs/features.jar in classpath
import de.uni_kassel.features.ReferenceHandler; // requires Fujaba5/libs/features.jar in classpath
import de.upb.tools.sdm.*; // requires Fujaba5/libs/RuntimeTools.jar in classpath
import junit.framework.TestCase;


public class EeroDealsOneRoundTest extends TestCase
{



   /**
    * <pre>
    *           0..1     object_Artjom     0..1
    * EeroDealsOneRoundTest ------------------------> Player
    *           test               Artjom
    * </pre>
    */
   public static final String PROPERTY_ARTJOM = "Artjom";

   @Property( name = PROPERTY_ARTJOM, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Player Artjom;

   @Property( name = PROPERTY_ARTJOM )
   public boolean setArtjom (Player value)
   {
      boolean changed = false;

      if (this.Artjom != value)
      {
      
         Player oldValue = this.Artjom;
         this.Artjom = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_ARTJOM )
   public EeroDealsOneRoundTest withArtjom (Player value)
   {
      setArtjom (value);
      return this;
   }

   public Player getArtjom ()
   {
      return this.Artjom;
   }

   /**
    * <pre>
    *           0..1     object_C8     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               C8
    * </pre>
    */
   public static final String PROPERTY_C8 = "C8";

   @Property( name = PROPERTY_C8, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card C8;

   @Property( name = PROPERTY_C8 )
   public boolean setC8 (Card value)
   {
      boolean changed = false;

      if (this.C8 != value)
      {
      
         Card oldValue = this.C8;
         this.C8 = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_C8 )
   public EeroDealsOneRoundTest withC8 (Card value)
   {
      setC8 (value);
      return this;
   }

   public Card getC8 ()
   {
      return this.C8;
   }

   /**
    * <pre>
    *           0..1     object_CA     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               CA
    * </pre>
    */
   public static final String PROPERTY_CA = "CA";

   @Property( name = PROPERTY_CA, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card CA;

   @Property( name = PROPERTY_CA )
   public boolean setCA (Card value)
   {
      boolean changed = false;

      if (this.CA != value)
      {
      
         Card oldValue = this.CA;
         this.CA = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_CA )
   public EeroDealsOneRoundTest withCA (Card value)
   {
      setCA (value);
      return this;
   }

   public Card getCA ()
   {
      return this.CA;
   }

   /**
    * <pre>
    *           0..1     object_D10     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               D10
    * </pre>
    */
   public static final String PROPERTY_D10 = "D10";

   @Property( name = PROPERTY_D10, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card D10;

   @Property( name = PROPERTY_D10 )
   public boolean setD10 (Card value)
   {
      boolean changed = false;

      if (this.D10 != value)
      {
      
         Card oldValue = this.D10;
         this.D10 = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_D10 )
   public EeroDealsOneRoundTest withD10 (Card value)
   {
      setD10 (value);
      return this;
   }

   public Card getD10 ()
   {
      return this.D10;
   }

   /**
    * <pre>
    *           0..1     object_D9     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               D9
    * </pre>
    */
   public static final String PROPERTY_D9 = "D9";

   @Property( name = PROPERTY_D9, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card D9;

   @Property( name = PROPERTY_D9 )
   public boolean setD9 (Card value)
   {
      boolean changed = false;

      if (this.D9 != value)
      {
      
         Card oldValue = this.D9;
         this.D9 = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_D9 )
   public EeroDealsOneRoundTest withD9 (Card value)
   {
      setD9 (value);
      return this;
   }

   public Card getD9 ()
   {
      return this.D9;
   }

   /**
    * <pre>
    *           0..1     object_DA     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               DA
    * </pre>
    */
   public static final String PROPERTY_DA = "DA";

   @Property( name = PROPERTY_DA, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card DA;

   @Property( name = PROPERTY_DA )
   public boolean setDA (Card value)
   {
      boolean changed = false;

      if (this.DA != value)
      {
      
         Card oldValue = this.DA;
         this.DA = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_DA )
   public EeroDealsOneRoundTest withDA (Card value)
   {
      setDA (value);
      return this;
   }

   public Card getDA ()
   {
      return this.DA;
   }

   /**
    * <pre>
    *           0..1     object_DJ     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               DJ
    * </pre>
    */
   public static final String PROPERTY_DJ = "DJ";

   @Property( name = PROPERTY_DJ, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card DJ;

   @Property( name = PROPERTY_DJ )
   public boolean setDJ (Card value)
   {
      boolean changed = false;

      if (this.DJ != value)
      {
      
         Card oldValue = this.DJ;
         this.DJ = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_DJ )
   public EeroDealsOneRoundTest withDJ (Card value)
   {
      setDJ (value);
      return this;
   }

   public Card getDJ ()
   {
      return this.DJ;
   }

   /**
    * <pre>
    *           0..1     object_DK     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               DK
    * </pre>
    */
   public static final String PROPERTY_DK = "DK";

   @Property( name = PROPERTY_DK, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card DK;

   @Property( name = PROPERTY_DK )
   public boolean setDK (Card value)
   {
      boolean changed = false;

      if (this.DK != value)
      {
      
         Card oldValue = this.DK;
         this.DK = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_DK )
   public EeroDealsOneRoundTest withDK (Card value)
   {
      setDK (value);
      return this;
   }

   public Card getDK ()
   {
      return this.DK;
   }

   /**
    * <pre>
    *           0..1     object_DQ     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               DQ
    * </pre>
    */
   public static final String PROPERTY_DQ = "DQ";

   @Property( name = PROPERTY_DQ, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card DQ;

   @Property( name = PROPERTY_DQ )
   public boolean setDQ (Card value)
   {
      boolean changed = false;

      if (this.DQ != value)
      {
      
         Card oldValue = this.DQ;
         this.DQ = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_DQ )
   public EeroDealsOneRoundTest withDQ (Card value)
   {
      setDQ (value);
      return this;
   }

   public Card getDQ ()
   {
      return this.DQ;
   }

   /**
    * <pre>
    *           0..1     object_Deck     0..1
    * EeroDealsOneRoundTest ------------------------> Deck
    *           test               Deck
    * </pre>
    */
   public static final String PROPERTY_DECK = "Deck";

   @Property( name = PROPERTY_DECK, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Deck Deck;

   @Property( name = PROPERTY_DECK )
   public boolean setDeck (Deck value)
   {
      boolean changed = false;

      if (this.Deck != value)
      {
      
         Deck oldValue = this.Deck;
         this.Deck = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_DECK )
   public EeroDealsOneRoundTest withDeck (Deck value)
   {
      setDeck (value);
      return this;
   }

   public Deck getDeck ()
   {
      return this.Deck;
   }

   /**
    * <pre>
    *           0..1     object_Eero     0..1
    * EeroDealsOneRoundTest ------------------------> Dealer
    *           test               Eero
    * </pre>
    */
   public static final String PROPERTY_EERO = "Eero";

   @Property( name = PROPERTY_EERO, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Dealer Eero;

   @Property( name = PROPERTY_EERO )
   public boolean setEero (Dealer value)
   {
      boolean changed = false;

      if (this.Eero != value)
      {
      
         Dealer oldValue = this.Eero;
         this.Eero = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_EERO )
   public EeroDealsOneRoundTest withEero (Dealer value)
   {
      setEero (value);
      return this;
   }

   public Dealer getEero ()
   {
      return this.Eero;
   }

   /**
    * <pre>
    *           0..1     object_Eero     0..1
    * EeroDealsOneRoundTest ------------------------> Player
    *           test               Eero
    * </pre>
    */
   public static final String PROPERTY_EERO = "Eero";

   @Property( name = PROPERTY_EERO, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Player Eero;

   @Property( name = PROPERTY_EERO )
   public boolean setEero (Player value)
   {
      boolean changed = false;

      if (this.Eero != value)
      {
      
         Player oldValue = this.Eero;
         this.Eero = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_EERO )
   public EeroDealsOneRoundTest withEero (Player value)
   {
      setEero (value);
      return this;
   }

   public Player getEero ()
   {
      return this.Eero;
   }

   /**
    * <pre>
    *           0..1     object_H10     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               H10
    * </pre>
    */
   public static final String PROPERTY_H10 = "H10";

   @Property( name = PROPERTY_H10, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card H10;

   @Property( name = PROPERTY_H10 )
   public boolean setH10 (Card value)
   {
      boolean changed = false;

      if (this.H10 != value)
      {
      
         Card oldValue = this.H10;
         this.H10 = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_H10 )
   public EeroDealsOneRoundTest withH10 (Card value)
   {
      setH10 (value);
      return this;
   }

   public Card getH10 ()
   {
      return this.H10;
   }

   /**
    * <pre>
    *           0..1     object_H7     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               H7
    * </pre>
    */
   public static final String PROPERTY_H7 = "H7";

   @Property( name = PROPERTY_H7, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card H7;

   @Property( name = PROPERTY_H7 )
   public boolean setH7 (Card value)
   {
      boolean changed = false;

      if (this.H7 != value)
      {
      
         Card oldValue = this.H7;
         this.H7 = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_H7 )
   public EeroDealsOneRoundTest withH7 (Card value)
   {
      setH7 (value);
      return this;
   }

   public Card getH7 ()
   {
      return this.H7;
   }

   /**
    * <pre>
    *           0..1     object_HK     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               HK
    * </pre>
    */
   public static final String PROPERTY_HK = "HK";

   @Property( name = PROPERTY_HK, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card HK;

   @Property( name = PROPERTY_HK )
   public boolean setHK (Card value)
   {
      boolean changed = false;

      if (this.HK != value)
      {
      
         Card oldValue = this.HK;
         this.HK = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_HK )
   public EeroDealsOneRoundTest withHK (Card value)
   {
      setHK (value);
      return this;
   }

   public Card getHK ()
   {
      return this.HK;
   }

   /**
    * <pre>
    *           0..1     object_HQ     0..1
    * EeroDealsOneRoundTest ------------------------> Card
    *           test               HQ
    * </pre>
    */
   public static final String PROPERTY_HQ = "HQ";

   @Property( name = PROPERTY_HQ, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Card HQ;

   @Property( name = PROPERTY_HQ )
   public boolean setHQ (Card value)
   {
      boolean changed = false;

      if (this.HQ != value)
      {
      
         Card oldValue = this.HQ;
         this.HQ = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_HQ )
   public EeroDealsOneRoundTest withHQ (Card value)
   {
      setHQ (value);
      return this;
   }

   public Card getHQ ()
   {
      return this.HQ;
   }

   /**
    * <pre>
    *           0..1     object_Ulno     0..1
    * EeroDealsOneRoundTest ------------------------> Player
    *           test               Ulno
    * </pre>
    */
   public static final String PROPERTY_ULNO = "Ulno";

   @Property( name = PROPERTY_ULNO, kind = ReferenceHandler.ReferenceKind.TO_ONE,
         adornment = ReferenceHandler.Adornment.NONE)
   private Player Ulno;

   @Property( name = PROPERTY_ULNO )
   public boolean setUlno (Player value)
   {
      boolean changed = false;

      if (this.Ulno != value)
      {
      
         Player oldValue = this.Ulno;
         this.Ulno = value;
         changed = true;
      
      }
      return changed;
   }

   @Property( name = PROPERTY_ULNO )
   public EeroDealsOneRoundTest withUlno (Player value)
   {
      setUlno (value);
      return this;
   }

   public Player getUlno ()
   {
      return this.Ulno;
   }

   public void setUp ()
   {
      boolean fujaba__Success = false;
      Dealer Eero = null;
      Deck Deck = null;
      Player Ulno = null;
      Player Artjom = null;
      Card D9 = null;
      Card D10 = null;
      Card DQ = null;
      Card DK = null;
      Card H10 = null;
      Card C8 = null;
      Card HQ = null;
      Card HK = null;
      Card DA = null;
      Card DJ = null;
      Card CA = null;
      Card H7 = null;

      // story pattern 
      try 
      {
         fujaba__Success = false; 

         // create object Eero
         Eero = new Dealer ( );

         // create object Deck
         Deck = new Deck ( );

         // create object Eero
         Eero = new Player ( );

         // create object Ulno
         Ulno = new Player ( );

         // create object Artjom
         Artjom = new Player ( );

         // create object D9
         D9 = new Card ( );

         // create object D10
         D10 = new Card ( );

         // create object DQ
         DQ = new Card ( );

         // create object DK
         DK = new Card ( );

         // create object H10
         H10 = new Card ( );

         // create object C8
         C8 = new Card ( );

         // create object HQ
         HQ = new Card ( );

         // create object HK
         HK = new Card ( );

         // create object DA
         DA = new Card ( );

         // create object DJ
         DJ = new Card ( );

         // create object CA
         CA = new Card ( );

         // create object H7
         H7 = new Card ( );

         // create link holds from Deck to Eero
         Deck.setDealer (Eero);

         // create link is from Eero to Eero
         Eero.setDealer (Eero);

         // create link object_Eero from this to Eero
         this.setEero (Eero);

         // create link right of from Ulno to Eero
         Ulno.setPlayer (Eero);

         // create link right of from Artjom to Eero
         Artjom.setPlayer (Eero);

         // create link object_Eero from this to Eero
         this.setEero (Eero);

         // create link right of from Ulno to Artjom
         Ulno.setPlayer (Artjom);

         // create link object_Artjom from this to Artjom
         this.setArtjom (Artjom);

         // create link object_Ulno from this to Ulno
         this.setUlno (Ulno);

         // create link on top from D9 to Deck
         D9.setDeck (Deck);

         // create link object_Deck from this to Deck
         this.setDeck (Deck);

         // create link on top of from D10 to D9
         D10.setCard (D9);

         // create link object_D9 from this to D9
         this.setD9 (D9);

         // create link on top of from DQ to D10
         DQ.setCard (D10);

         // create link object_D10 from this to D10
         this.setD10 (D10);

         // create link on top of from DK to DQ
         DK.setCard (DQ);

         // create link object_DQ from this to DQ
         this.setDQ (DQ);

         // create link on top of from H10 to DK
         H10.setCard (DK);

         // create link object_DK from this to DK
         this.setDK (DK);

         // create link on top of from C8 to H10
         C8.setCard (H10);

         // create link object_H10 from this to H10
         this.setH10 (H10);

         // create link on top of from HQ to C8
         HQ.setCard (C8);

         // create link object_C8 from this to C8
         this.setC8 (C8);

         // create link on top of from HK to HQ
         HK.setCard (HQ);

         // create link object_HQ from this to HQ
         this.setHQ (HQ);

         // create link on top of from DA to HK
         DA.setCard (HK);

         // create link object_HK from this to HK
         this.setHK (HK);

         // create link on top of from DJ to DA
         DJ.setCard (DA);

         // create link object_DA from this to DA
         this.setDA (DA);

         // create link on top of from CA to DJ
         CA.setCard (DJ);

         // create link object_DJ from this to DJ
         this.setDJ (DJ);

         // create link on top of from H7 to CA
         H7.setCard (CA);

         // create link object_CA from this to CA
         this.setCA (CA);

         // create link object_H7 from this to H7
         this.setH7 (H7);

         fujaba__Success = true;
      }
      catch ( JavaSDMException fujaba__InternalException )
      {
         fujaba__Success = false;
      }

   }

   public void testEeroDealsOneRound ()
   {
      boolean fujaba__Success = false;

      // assert result situation
   }

   public void removeYou()
   {
      this.setArtjom (null);
      this.setC8 (null);
      this.setCA (null);
      this.setD10 (null);
      this.setD9 (null);
      this.setDA (null);
      this.setDJ (null);
      this.setDK (null);
      this.setDQ (null);
      this.setDeck (null);
      this.setEero (null);
      this.setEero (null);
      this.setH10 (null);
      this.setH7 (null);
      this.setHK (null);
      this.setHQ (null);
      this.setUlno (null);
   }
}


